### ISSUE TITLE
Options (features request).

### ISSUE THREAD

**Issue by Achaean** [hellzerg/hashing#1]
**Hi!** :-)

Hashing is a very good hashing utility.
In order to be perfect (at my opinion), additionally needs:
1) A SHA512 sum. Some sites offering this option too.
2) An option for entering the hash sum and comparing against the results (if it's true or false).
3) An option for choosing which hashes you want to calculate. Calculating all of them, is probably a waste of time, for big files (eg. a Linux DVD ISO, can be >4GB.

And optionally (but not absolutely needed):
1) Option to close it, on a tray icon. Reloading it every time can be a waste of time.
2) Option to assign it high priority. (Again, useful for big files).

**Keep up the good work!!!** ;-)
A.

**Comment by hellzerg** [comment]
Hello,

I've already implemented these features, even the optional ones!

Do you want to try it?

Thanks for the suggestions, anyway!

**Comment by Achaean** [comment]
I'd love to! :-)

**Comment by Achaean** [comment]
I tried it. Really nice work!!! :-)

Just one question:
I pressed "Compare" and in the new box it opened, I choose a hash value (lets say SHA1) and I suppose I have to enter the value to "Expected hash:" text box and press the "Compare" button.

The problem is that I can't paste it there. I tried both with the keyboard (clicking inside the text box and pressing Ctrl-V) and mouse (right clicking -> Paste).

Am I doing something wrong? :-)
A.

**Comment by hellzerg** [comment]
What? How? It's pasting just fine here..

**Comment by Achaean** [comment]
My system is Win 10 Pro v.10.0.15063 x64 and I tested it also at another machine Win 10 Home v.10.0.15063 x64.
At the 2nd machine, "Paste" works, but clicking "Compare" doesn't do something.

I tried (at my own system), at Safe Mode and at diagnostic restart (with MSCONFIG), with non-MS drivers disabled.
In both cases pasting was possible, but "Compare" button didn't do anything. :-(
A.

**Comment by hellzerg** [comment]
Did you drag n' drop any file on the main form? It needs at least one file, so it can compare against it.

Look at the picture:
![capture](https://user-images.githubusercontent.com/3146835/30820970-4865cb1a-a22c-11e7-80b0-ee70b2e61608.PNG)

**Comment by Achaean** [comment]
Yes I did it.
Results remains empty here.
![screenshot_1](https://user-images.githubusercontent.com/3608053/30822177-968feaf6-a230-11e7-9d3f-23b5b8ad66d5.png)

**Comment by hellzerg** [comment]
Try converting the SHA1 hash to upper case and try again. Let's see if that works.

**Comment by Achaean** [comment]
**Success!!!** :-)

![screenshot_2](https://user-images.githubusercontent.com/3608053/30822557-e175ec68-a231-11e7-9052-c5a585140cca.png)

**Comment by hellzerg** [comment]
Well, I already fixed that! :D
