### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by lagame** [hellzerg/hashing#11]
I downloaded the hashing from [this link](https://github.com/hellzerg/hashing/releases/download/2.1/Hashing-2.1.exe) and uploaded it to virustotal.com, and it claimed that it has a Trojan.Malware.300983.susgen, is it safe to run it?
![image](https://user-images.githubusercontent.com/1186394/128719094-287004a2-a2a6-4547-8346-3146ad996166.png)

**Comment by onmyouji** [comment]
It's safe, only 1 vendor detected it as malware. It's a false positive.

When using virustotal, you only have to worry if you get warning from multiple vendors.

**Comment by hellzerg** [comment]
It's completely safe.
