### ISSUE TITLE
Compare multiple group identical files, All files be grouped together into one group.

### ISSUE THREAD

**Issue by vactiger** [hellzerg/hashing#12]
### Version

2.1

### Screenshots

![image](https://user-images.githubusercontent.com/49655153/132971524-473195ff-f124-4940-b9f5-ad338f236bbd.png)

![image](https://user-images.githubusercontent.com/49655153/132971534-590bddd5-abfe-47c1-b8dd-c39df16f91c4.png)

### Reproduce

- `00.txt` and `00 backup.txt` are identical.
- `11.txt` and `11 backup.txt` are identical.
- `00.txt` != `11.txt`.

Click "Find Identicals" button.

### Expected

Get two groups.

### Actual

Get one group, and the group title is one of them.

---

My English is not very good, please forgive me.

Thank you.

**Comment by hellzerg** [comment]
Fixed. Updated to v2.2.
