### ISSUE TITLE
one request: when drag and drop json file, just list them (no check if file exist and no re-calculating)

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#13]
so i can compare two offline pc which files are the same.
step1.on pc1, drag and drop files and save as json.
step2.on pc2, drag and drop pc1.json file and drag and drop pc2 files.
step3.on pc2, click "Find Identicals" button, done.

**Comment by hellzerg** [comment]
This analyzing process feature has been requested here: https://github.com/hellzerg/hashing/issues/8

I don't understand what do you mean, can you be more specific please?

**Comment by user336598776** [comment]
for example, on PC1 i drag and drop "E:\abc" folder and save as "e.json" file. (01.png)
![01](https://user-images.githubusercontent.com/76890358/150495228-1788e57c-c238-4a3c-9411-3f8478e554a8.png)


i copy the "e.json" and this program to PC2(another computer which there is no "E:\abc" folder and files).
on PC2, i run this program and drag and drop "e.json" files and click "yes", it only display "Calculating..." and does not list items of "e.json" file. (02.png)
![02](https://user-images.githubusercontent.com/76890358/150495275-8299514e-37cd-4d90-bd95-c330b0518456.png)


the request is that after drag and drop json file, just list items of json file even the item doesn't exist.
sry for my bad english.

**Comment by hellzerg** [comment]
Okay, I understand now. I will do it in the next 2-3 days.

**Comment by hellzerg** [comment]
Requested feature, along with some maintenance changes and fixes have been released in v2.5!
