### ISSUE TITLE
v2.5 request 1: "List JSON files" and drag and drop new folder, the json list doesn't disappeared. request 2: "List JSON files" can click "Find Identicals" to compare the same hash.

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#14]
on PC1 i drag and drop "E:\abc" folder and save as "e.json" file.
i copy the "e.json" file and this program to PC2(another computer which there is no "E:\abc" folder and files).
on PC2, i run this program and drag and drop "e.json" file and click "List JSON files". the list1 is:
E:\abc\a.txt
E:\abc\b.txt
E:\abc\test\1.txt
E:\abc\test\2.txt
E:\abc\test\3.txt
(01.png)
![01](https://user-images.githubusercontent.com/76890358/150663033-9e8f3512-75ea-4084-988b-ba33d95c21ac.png)

on PC2, i drag and drop "D:\123" folder, the list1 disappeared and the list2 is:
D:\123\t1.txt
D:\123\t2.txt
(02.png)
![02](https://user-images.githubusercontent.com/76890358/150663037-ec2f05b4-a87d-4b28-b49c-3e7c0c7b694a.png)

it would be nice if the final list is:
E:\abc\a.txt
E:\abc\b.txt
E:\abc\test\1.txt
E:\abc\test\2.txt
E:\abc\test\3.txt
D:\123\t1.txt
D:\123\t2.txt

if so, i can click "Find Identicals" button to compare the same hash even if the item(filepath) doesn't exist.
(03.png)
![03](https://user-images.githubusercontent.com/76890358/150663040-b5a8115c-68ae-4236-aa39-030f444cb797.png)

------------

request 2 is "List JSON files" can click "Find Identicals" to compare the same hash.
on PC1 i drag and drop "E:\abc123" folder and save as "a1.json" file.
(a1.png)
![a1](https://user-images.githubusercontent.com/76890358/150685979-4b3ade8e-fd6e-4b6e-a42d-d4ca039012ac.png)

restart the program, drag and drop "a1.json" file and click "List JSON files" and click "Find Identicals" button, it display "No identical files have been found!". however, "a.txt" and "t1.txt" are the same hash files.
(a2.png)
![a2](https://user-images.githubusercontent.com/76890358/150685987-de83a440-c05b-45ca-93de-4e4335d4750c.png)

**Comment by hellzerg** [comment]
Okay, done. Update to v2.6.
