### ISSUE TITLE
Q1: what does "Remove dashes" mean? Q2: do you wanna make multi languages support?

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#15]
Q1:
i drag and drop "abc123" folder and click "Compare" button and Paste a hash.
i don't know "Remove dashes" option means what?
![Remove dashes](https://user-images.githubusercontent.com/76890358/151300057-eeb9961f-6d0b-4a8a-b7e8-a6d53a67a08d.png)

Q2:
multi lang support such as Simplified Chinese(zh-CN)?
someone can only understand Chinese words.
i can translate to zh-CN lang file.

**Comment by hellzerg** [comment]
**Remove dashes** option just removes the "-" between hash characters, if there are any.

Multi-language support is something I can do.

**Comment by user336598776** [comment]
> **Remove dashes** option just removes the "-" between hash characters, if there are any.
> 
> Multi-language support is something I can do.

waiting for your Multi-language support new version release

**Comment by hellzerg** [comment]
Please, translate this list to your preferred language.

[hashing-en.txt](https://github.com/hellzerg/hashing/files/7948994/hashing-en.txt)

**Comment by user336598776** [comment]
> Please, translate this list to your preferred language.
> 
> [hashing-en.txt](https://github.com/hellzerg/hashing/files/7948994/hashing-en.txt)

i uploaded two files, hashing-cn_utf8.txt and hashing-cn_unicode.txt, maybe utf8 is the one.
[hashing-cn_utf8.txt](https://github.com/hellzerg/hashing/files/7949534/hashing-cn_utf8.txt)
[hashing-cn_unicode.txt](https://github.com/hellzerg/hashing/files/7949536/hashing-cn_unicode.txt)

**Comment by hellzerg** [comment]
Just a little more for translation.

[extras.txt](https://github.com/hellzerg/hashing/files/7951202/extras.txt)

**Comment by user336598776** [comment]
> Just a little more for translation.
> 
> [extras.txt](https://github.com/hellzerg/hashing/files/7951202/extras.txt)

i uploaded two files, maybe utf8 is the one.
[extras_cn_utf8.txt](https://github.com/hellzerg/hashing/files/7954868/extras_cn_utf8.txt)
[extras_cn_unicode.txt](https://github.com/hellzerg/hashing/files/7954869/extras_cn_unicode.txt)

**Comment by hellzerg** [comment]
Done. Update to 2.7.
