### ISSUE TITLE
v2.7 need some fix

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#16]
fix1:
when select a theme, there's no language selection.
when select a language, there's no theme selection.
![fix1](https://user-images.githubusercontent.com/76890358/151643345-c55125fd-c8e3-40bb-8323-2b526f677c64.png)

fix2:
"Identical files" window is still english not chinese.
(english) --> (chinese)
Identical files --> 相同的文件
Copy --> 复制
Save as JSON --> 另存为JSON
![fix2](https://user-images.githubusercontent.com/76890358/151643349-e5231f83-b0a7-4003-83bd-41c1e5c46751.png)

fix3:
i fix some part of "CN.json" file and uploaded here:
[CN.json.txt](https://github.com/hellzerg/hashing/files/7963026/CN.json.txt)

**Comment by hellzerg** [comment]
Everything is fixed. Update using the app's updater.
