### ISSUE TITLE
sry for my mistake, v2.8 need two fix

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#17]
fix1:
"lblversion": "Version: {VN}",
"lblversion": "版本: {VN}",
when i first run this program and select chinese, it's "版本: 2.8", but after i close the program and run it again, it display "Version: 2.8".
![fix1](https://user-images.githubusercontent.com/76890358/151653523-950abead-4bd0-4ed3-a7f3-43d482899892.png)

fix2:
sry for my mistake, i uploaded new "CN.json":
[CN.json.txt](https://github.com/hellzerg/hashing/files/7963253/CN.json.txt)

"button7": "确定",
"chkSingleInstance": "只能运行一个本程序",
it's better to understand for chinese people.

**Comment by hellzerg** [comment]
Done. I hope that's all the fixes for Chinese,
