### ISSUE TITLE
v3.1 GUI doesn't display Korean filename,filepath on Win7

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#19]
drag and drop "kr한국.txt" file, and the GUI doesn't display "한국" word.
![20220209](https://user-images.githubusercontent.com/76890358/153129311-c0fa540d-1656-4f60-a888-c4d00a3f22a9.png)
![20220209b](https://user-images.githubusercontent.com/76890358/153130973-54518a4d-c483-4476-b1c1-26ebd2add097.png)

save as json and open it using notepad, it's ok.

**Comment by hellzerg** [comment]
I tried it on my setup, and it's working fine.
![image](https://user-images.githubusercontent.com/3146835/153161807-561b6af6-f8a2-4877-9903-9305e302f99a.png)

Maybe you need to setup your default encoding language? See below:
![image](https://user-images.githubusercontent.com/3146835/153162196-c5482a7b-1a85-4ead-a187-31980e2b3a2f.png)

**Comment by user336598776** [comment]
after setting Korean and restart computer, it works but can't display Chinese words correctly.


without this system setting, i drag and drop json file and click "Analyze JSON files" button, the small window display Korean words correctly.
![20220209c](https://user-images.githubusercontent.com/76890358/153184822-c8283b0f-a7cc-4341-bf20-a49ca2df4103.png)

so maybe it's possible to display Korean words without any system setting.

**Comment by hellzerg** [comment]
Previous version (3.0) works or not?

**Comment by user336598776** [comment]
v3.0 works.
![v3 0](https://user-images.githubusercontent.com/76890358/153194003-4225a6d0-d67f-435d-98ae-5d0050e5ceaa.png)

**Comment by hellzerg** [comment]
But it does the same, not showing chinese characters.

**Comment by user336598776** [comment]
chinese characters "新建文件夹" works,
korean characters "한국" not work.

**Comment by hellzerg** [comment]
Wait... the program is in chinese, not korean. It's not translated to korean.

**Comment by user336598776** [comment]
> Wait... the program is in chinese, not korean. It's not translated to korean.

but the small window display korean characters correctly, small window is utf8 display? maybe the main windows path can utf8 display.

**Comment by hellzerg** [comment]
Maybe it's Windows 7 issue? Have you tried it on Windows 10?

**Comment by user336598776** [comment]
> Maybe it's Windows 7 issue? Have you tried it on Windows 10?

yes, that's win7's problem. win10pro(20h2) works perfect.
![win10pro20h2works](https://user-images.githubusercontent.com/76890358/153224831-74e196d6-2426-4758-b1bd-166db6fcfc9b.png)

**Comment by hellzerg** [comment]
Maybe, try to update .NET framework through Windows Update. Or install latest .NET 4.8. It might fix the issue on Windows 7.

**Comment by user336598776** [comment]
already installed .Net Framework 4.8 on win7pro sp1

**Comment by user336598776** [comment]
drag and drop saved utf8 json file and click "Analyze JSON files" button, the small window doesn't display Korean words correctly in v2.9, but v3.0 and v3.1 correctly.
![ver2 9](https://user-images.githubusercontent.com/76890358/153580910-486d0687-5d0a-4295-83c0-d570c10ae144.png)
![ver3 0](https://user-images.githubusercontent.com/76890358/153580927-ead4ef4e-3a77-4193-bb23-1610e4306232.png)
![ver3 1](https://user-images.githubusercontent.com/76890358/153580941-98563b53-24d8-46fb-aab6-f09248607a52.png)

maybe you can use the same tech to display filepath in main window for win7.

**Comment by user336598776** [comment]
ver2.6
![ver2 6](https://user-images.githubusercontent.com/76890358/153653606-b28dcfd3-b0c4-41b5-b408-ca689526a8ef.png)

**Comment by hellzerg** [comment]
[Hashing-TEST.zip](https://github.com/hellzerg/hashing/files/8053191/Hashing-TEST.zip)

Can you try this test build, if it's okay?

**Comment by user336598776** [comment]
> [Hashing-TEST.zip](https://github.com/hellzerg/hashing/files/8053191/Hashing-TEST.zip)
> 
> Can you try this test build, if it's okay?

Hashing-TEST.exe can display some korean word but need some fix:
"D:\新建文件夹\kr한국." to "D:\新建文件夹\kr한국.txt"
"D:\新建文件夹\한국kr\kr한" to "D:\新建文件夹\한국kr\kr한국.txt"
and "Find Identicals" need some fix too:
"D:\新建文件夹\kr한" to "D:\新建文件夹\kr한국.txt"
"D:\新建文件夹\한국kr\kr" to "D:\新建文件夹\한국kr\kr한국.txt"
![test1](https://user-images.githubusercontent.com/76890358/153710203-5f3a18b2-df69-46d7-89d4-353d035fc491.png)

**Comment by user336598776** [comment]
Hashing-TEST2, the main window display well
![test2a](https://user-images.githubusercontent.com/76890358/153714124-7ccc42d3-a9e1-44ee-94fd-716c6d0a5375.png)

but "Find Identicals" need some fix:
"D:\新建文件夹\kr한국." to "D:\新建文件夹\kr한국.txt"
"D:\新建文件夹\한국kr\kr한" to "D:\新建文件夹\한국kr\kr한국.txt"
![test2b](https://user-images.githubusercontent.com/76890358/153714127-c483af41-7b21-44a7-b5e6-64d888444c29.png)

**Comment by hellzerg** [comment]
[Hashing-TEST3.zip](https://github.com/hellzerg/hashing/files/8053586/Hashing-TEST3.zip)

I hope this is okay.

**Comment by hellzerg** [comment]
Okay, I am gonna update it properly.
