### ISSUE TITLE
Option for selecting hash type at "Compare files" window (feature request).

### ISSUE THREAD

**Issue by Achaean** [hellzerg/hashing#2]
**Hi!** :-)

When opening the "Compare files" window, the default MD5 hash is always selected.
(Screenshot attached).

It wold be nice at my opinion, if there was an option, for choosing the default hash type, or just remembering what hash type last used and autochoosing it.

Personally speaking, the most frequent hash type I'm dealing with, is SHA1, and every time I have to choose it again.

**TIA!** :-)
A.

![screenshot](https://user-images.githubusercontent.com/3608053/34104127-f100ecc0-e3f7-11e7-8eb3-5239899c1a6f.png)

**Comment by hellzerg** [comment]
I'll do that, but I feel more features should be implemented before I increment the version number.
What else do you have in mind?

**Comment by hellzerg** [comment]
Ok, added!

**Comment by Achaean** [comment]
**Great! THANKS!!!** :-)

I can't think of an actual addition-improvement.
I'm fond of Unix philosophy for "one (preferably small) program doing one thing". I don't like very much software suites or bloated programs and I think Hashing is already functional and mature.

What I could think is just a couple of final touches:

1) Maybe an "About" box (or alternatively a README.TXT file).
Primary for indicating your Homepage and Personal project page (here at GitHub).

2) Or maybe a "New version available" checker (or alternatively you can setup an RSS feed on your page (or an old-school maillist), (since I don't know if GitHub supports this feature)).

**Best wishes**, for the holiday season!!! :-)
A.

**Comment by hellzerg** [comment]
Actually, there is a hidden about box, just click the large icon in top-left corner!
As for the update checker, I don't feel like adding one. 

Check here: [https://github.com/hellzerg/deadmoon-launcher]()

**Comment by Achaean** [comment]
Oh...I didn't noticed it!
**Nice!!!** :-)

BTW, maybe yet another (not very important) feature, is saving the window position between sessions.
**Bye!** :-)
A.

**Comment by hellzerg** [comment]
I'll think about it.
Thanks!
