### ISSUE TITLE
v3.3 need to fix right click "Show file" if there is a "," or "=" character in the path,filename

### ISSUE THREAD

**Issue by user336598776** [hellzerg/hashing#20]
if the path or filename contain "," or "=" character, right click "Show file", it doesn't show(locate) the file.
![,=](https://user-images.githubusercontent.com/76890358/153994067-6e7d0a7c-85b9-4445-ae51-ab6ccb90b5e7.png)

i've tested all symbol character on the keyboard and found only two problem character("," "=").

**Comment by hellzerg** [comment]
Yeah, patched in upstream. Update to v3.4.
