### ISSUE TITLE
[Bug 3.4] Crash When Input Large Number of Files

### ISSUE THREAD

**Issue by Biglulux** [hellzerg/hashing#23]
I dragged a directory containing a very large amount of files (88,000) into the program. It seemed that the calculation of hashes proceeded fine, as the number increased until it reached maximum at 88000/88000. However, once that was completed the program went unresponsive as it tried to display the list of files. I waited for a while, but it continued to hang at the display of 88000/88000 and did not proceed.

OS: Windows 10 Pro

**Comment by hellzerg** [comment]
It just needed extra time to process the large amount of files... what do you expect?

**Comment by Biglulux** [comment]
Alright, I let it process for about 45 mins or so and it worked. Thanks.

**Comment by hellzerg** [comment]
Will examine if it can be improved.

**Comment by hellzerg** [comment]
It should be much faster now in v3.5.
