### ISSUE TITLE
Text blurry / Display scaling support

### ISSUE THREAD

**Issue by BycreatinganaccountyouagreetotheTerms** [hellzerg/hashing#25]
Hi,

Thanks for making this great program. Out of all that I tried, this one is the best.

I notice that the text looks a bit blurry. Is this because it doesn't support high DPI monitors or display scaling?

Thanks again.

**Comment by hellzerg** [comment]
Do you have Windows 10 or 11?

@BycreatinganaccountyouagreetotheTerms

**Comment by BycreatinganaccountyouagreetotheTerms** [comment]
Hi,

I am running Windows 10 22H2. I have attached a screenshot. It is not extremely blurry, but does seem a little blurry to me.
I have Windows display scaling at 150%.

![image](https://user-images.githubusercontent.com/120150565/210728878-b7ccfbd4-2dd0-4cd2-a750-570556aacd0b.png)

**Comment by hellzerg** [comment]
Custom scaling set to 150%?

@BycreatinganaccountyouagreetotheTerms

**Comment by BycreatinganaccountyouagreetotheTerms** [comment]
Not really custom scaling. Just using the drop down box on the main display settings page.

![image](https://user-images.githubusercontent.com/120150565/210730694-298e7242-0a47-4f03-8888-755b1e79c535.png)

**Comment by hellzerg** [comment]
Okay, I'll address the issue soon.

**Comment by BycreatinganaccountyouagreetotheTerms** [comment]
Please see screenshot below. Looks good. I thought it would be hard to fix but I'm glad I reported it.

![image](https://user-images.githubusercontent.com/120150565/210909855-68267397-8d7c-4145-aedd-d4bf4bc3c034.png)

**Comment by hellzerg** [comment]
Okay, I'll release a new version soon.

**Comment by hellzerg** [comment]
DPI support is available in v3.6. You can update through the app.

@BycreatinganaccountyouagreetotheTerms
