### ISSUE TITLE
Hashing(v3.7) calculating is slower than My Hash(v1.4.7)

### ISSUE THREAD

**Issue by vokins** [hellzerg/hashing#28]
Hashing(v3.7) calculating is slower than My Hash(v1.4.7)

My Hash(v1.4.7)：0m12.56s
`文件名称: zh-cn_windows_10_business_editions_version_22h2_updated_dec_2022_x64_dvd_cde06342.iso
文件大小: 5.55 GB (5,964,230,656 字节)
修改时间: 2022年12月24日，09:28:16
MD5: DF57824E84BB5375C9FC3AF4CAD58926
SHA1: C7C877210AC645C29574E1F110B0277932380A14
SHA256: 3CB92FAD8934C3C1A4827C290B4BC2C11331C84923B07FFECB2250C87CC4FC53
CRC32: C7BBE678
计算时间: 12.56s (474.78 MB/s)`
https://github.com/drag0n-app/MyHash

Hashing(v3.7)：0m22s
```
    "File": "E:\\Bakup\\zh-cn_windows_10_business_editions_version_22h2_updated_dec_2022_x64_dvd_cde06342.iso",
    "SHA1": "C7C877210AC645C29574E1F110B0277932380A14",
    "SHA256": "3CB92FAD8934C3C1A4827C290B4BC2C11331C84923B07FFECB2250C87CC4FC53"
```

**Comment by hellzerg** [comment]
10 seconds difference.

Which language the My Hash is coded into?

@vokins

**Comment by user336598776** [comment]
MyHash is from here:
https://github.com/drag0n-app/MyHash
https://github.com/drag0n-app/MyHash/raw/master/MyHash_1.4.7_Final_drag0n.7z

after upx unpacked,
Detect It Easy[DiE]: Embarcadero Delphi(10.2 Tokyo)
Exeinfo PE: Embarcadero Delphi compiler XE7 - 2014

btw, in my test, 7-Zip 64bit is faster than MyHash64.exe

**Comment by hellzerg** [comment]
I don't see much difference, because Hashing is an .NET app and not a native one.

The calculating time is pretty similar.

It can't be achieved something better than that.

@user336598776

**Comment by user336598776** [comment]
> I don't see much difference, because Hashing is an .NET app and not a native one.
> 
> The calculating time is pretty similar.
> 
> It can't be achieved something better than that.
> 
> @user336598776

this issue 28 is similar with issue [21](https://github.com/hellzerg/hashing/issues/21). 

smaragdus said:
C++ software will always be faster and lighter than C#

**Comment by hellzerg** [comment]
Exactly like you said.
