### ISSUE TITLE
On Top

### ISSUE THREAD

**Issue by smaragdus** [hellzerg/hashing#3]
To facilitate adding files via drag&drop I would like to suggest that you implement a new feature:

"**Stay on Top**" or just "**On Top**"

You may add it as an option in "Options" or even better as a button in program window (toggled on/off).

As a workaround I use an external tool- [SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu), screen:

![hashing 2 0 - 2018-05-14 - 030](https://user-images.githubusercontent.com/9025757/39972826-55650c6a-571f-11e8-9571-21c11fca7fcd.png)

but native support for "**On Top**" would be better.

**Off-topic**
I wrote a short review about [Hashing](https://github.com/hellzerg/hashing) at [The Portable Freeware Forum](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24195), I hope I didn't miss something essential.

**Comment by hellzerg** [comment]
Always on top feature will be available in the next version, 2.1, soon!

**Comment by smaragdus** [comment]
@hellzerg 
Thanks!
