### ISSUE TITLE
Single Instance

### ISSUE THREAD

**Issue by smaragdus** [hellzerg/hashing#4]
Currently, as of version [2.0](https://github.com/hellzerg/hashing/releases/tag/2.0) the users may run multiple instances of **Hashing**. This is not a bad thing but anyway, you may add a new check-box in "Options":

"**Single Instance**"

I suppose this option would not be hard to be implemented.

**Comment by hellzerg** [comment]
Single-instance feature will be available in the next version, 2.1, soon!
