### ISSUE TITLE
[Feature request] Progress bar, pause, and cancel option

### ISSUE THREAD

**Issue by vatterspun** [hellzerg/hashing#5]
Thought this would be a nice addition ...

Current behavior

1. Drag and drop files into program window
2. Text "Calculating" appears
3. When finished, displays files, directory, and hashes

Requested behavior

1. Drag and drop files into program window
2. A few elements:
 * Text "Calculating" appears along with a pause and cancel button
 * A bar or % value (or both) displaying progress as the files are read
 * A pause button stops operations until pause is pressed again or the cancel button is pressed
 * Cancel ends the hashing calculation operation and whatever files were evaluated before cancel was pressed are displayed
3. When finished, displays files, directory, and hashes along with total files and amount of data evaluated, as well as the time the process took (e.g. 32 files, 200 megs, 14 secs

**Comment by hellzerg** [comment]
I will consider adding it, sometime in the future, don't currently have the time for that.

**Comment by vatterspun** [comment]
> I will consider adding it, sometime in the future, don't currently have the time for that.

I saw that you covered a lot of other requests, thanks for that.

**Comment by hellzerg** [comment]
Total time, size estimation and Cancel feature implemented in v2.3.
