### ISSUE TITLE
Virustotal check issue

### ISSUE THREAD

**Issue by vatterspun** [hellzerg/hashing#7]
Setup: Win7x86

**Steps**:

1. Change hash to CRC32
2. Right click on an item and submit to virustotal

**Defect**: Error message: "VirusTotal recognizes files only by their MD5, SHA1 or SHA256 hash!"

**Expected behavior**: 

* Error message above but also prompt the user "Do you wish to switch to SHA256 for this operation?"  Once the user says yes, a browser window will be launched with the VirusTotal URL and the SHA256 value will appear in the Hashing program window.
* Just run SHA256 hash and open in the browser Window.

--

Also, for security reasons I'd also suggest not using the MD5/SHA1 capability and exclusively submit SHA256 values even if it slows down the program.  Both MD5 and SHA1 hashes are considered insecure.

**Comment by hellzerg** [comment]
Version 2.1 will include this functionality. Additionally, only SHA256 hashes will be passed through to VirusTotal!

**Comment by smaragdus** [comment]
Anyone should be aware that VirusTotal is a major privacy threat.

**Comment by vatterspun** [comment]
> Anyone should be aware that VirusTotal is a major privacy threat.

It is owned by Google so I have no doubt any data they can grab, they will.  Were you talking about this?  https://en.wikipedia.org/wiki/VirusTotal#Privacy

**Comment by smaragdus** [comment]
@vatterspun 
If you have time and patience for legal junk you may read [Privacy Policy ](https://support.virustotal.com/hc/en-us/articles/115002168385-Privacy-Policy) and [Terms of Service ](https://support.virustotal.com/hc/en-us/articles/115002145529-Terms-of-Service). I stopped using this service.

**Comment by hellzerg** [comment]
@smaragdus What's your opinion on [NoDistribute](http://nodistribute.com/)? Better alternative or not?

**Comment by smaragdus** [comment]
@hellzerg 
I have never used [NoDistribute](http://nodistribute.com/) so I don't have opinion. However it doesn't seem to be fully free ([Plans](http://nodistribute.com/plans/)). In the past I used [Jotti](https://virusscan.jotti.org/). Usually false positives are galore.
