### ISSUE TITLE
Batch analyze generated JSON files

### ISSUE THREAD

**Issue by vatterspun** [hellzerg/hashing#8]
I occasionally do batch file verification for file lists.  I generally put these on CDs to help detect scratches or external USB drives that I need to connect to untrusted machines.  The hash listings let me verify I have what I started out with.

Current behavior:

1. Drag-and-drop a JSON file
2. The program analyzes the JSON file itself and not the hashes listed within

Requested behavior

1. Drag-and-drop a JSON file
2. Check that the first few characters look like a file generated by the hashing program:

```
[
  {
    "File": " 
```
3. Prompt the user to run a check of the files listed in the locations inside the JSON file so, for example:

![image](https://user-images.githubusercontent.com/1289134/39976467-8af319c4-56f9-11e8-9d8f-6e95e1156bab.png)

... would have an MD5 and CRC32 analysis run. 

4. If the values were identical to the JSON file, a checkbox (or green text color) would appear to demonstrate that the file is the same.  If the values were different, an X (or red text color) would appear to demonstrate the files are different.

Additionally, it would be ideal if the file used relative links so that CD or USB drive locations whose letters change can still be checked.  e.g. "..\temp\Temp.7z"

I hope that's useful.

**Comment by hellzerg** [comment]
Functionality added! Version 2.1 is out! Please let me know if any bugs occur!

**Comment by vatterspun** [comment]
Cool, I'll try to run a test sometime soon.
