### ISSUE TITLE
[Feature request] Add files by method other than drag-and-drop (low priority)

### ISSUE THREAD

**Issue by vatterspun** [hellzerg/hashing#9]
This is low priority as I'm not currently having an issue but, having had some programs malfunction with regard to allowing drag-and-drop operations (e.g. https://github.com/fukuyori/ExcelPass/issues/19), I'd like to recommend an ability to add files and folders for analysis without drag-and-drop.

**Comment by hellzerg** [comment]
Actually, there is a browse button with a text field to add files in v2.1!

**Comment by vatterspun** [comment]
> there is a browse button with a text field to add files in v2.1!
Great, thank you
